name: DriveBackupV2
version: 1.4.0
api-version: 1.13
description: Uploads backups to Google Drive/OneDrive or by (S)FTP
main: ratismal.drivebackup.DriveBackup
author: MaxTheGinus
commands:
  drivebackup:
    description: View all DriveBackupV2 commands
    usage: /drivebackup